ImageCatch/projects/imagecatch/imca/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from imca import db
from imca.forms import UserCreateForm, UserLoginForm, UserChangeForm, PasswordForm
from imca.models import User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(userid=form.userid.data).first()
        user1 = User.query.filter_by(email=form.email.data).first()
        if not user and not user1:
            user = User(userid=form.userid.data,
                        password=generate_password_hash(form.password1.data),
                        username=form.username.data,
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            flash('이미 존재하는 사용자거나 이메일입니다.')
    return render_template('auth/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(userid=form.userid.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.route('/checkpasswd/', methods=('GET', 'POST'))
def checkpasswd():
    form = PasswordForm()
    user_id = session.get('user_id')
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.get_or_404(user_id) 
        if not check_password_hash(g.user.password, form.checkpassword.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            return redirect(url_for('auth.mypage'))
        flash(error)
    return render_template('auth/checkpasswd.html', form=form)

@bp.route('/find/')
def findpasswd():
    return render_template('auth/findpasswd.html')

@bp.route('/mypage/')
def mypage():
    return render_template('auth/mypage.html')

@bp.route('/mypage/change/<int:user_id>', methods=('GET', 'POST'))
def change(user_id):
    user = User.query.get_or_404(user_id)
    form = UserChangeForm()
    if request.method == 'POST':
        if form.validate_on_submit() and check_password_hash(g.user.password, form.old_password.data):
            user.password = generate_password_hash(form.new_password1.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.mypage', user_id=user_id))
        else:
            flash('기존 비밀번호가 틀렸습니다.')
    return render_template('auth/changepasswd.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/delete/<int:user_id>')
def delete(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    session.clear()
    return redirect(url_for('auth.login'))

ImageCatch/projects/imagecatch/imca/views/chart_views.py
from flask import Blueprint, url_for, render_template

bp = Blueprint('chart', __name__, url_prefix='/chart')

@bp.route('/')
def content():
    return render_template('chart.html')

ImageCatch/projects/imagecatch/imca/views/flask_upload.py
import shutil

from flask import Blueprint, url_for, render_template, request
from werkzeug.utils import secure_filename
from PIL import Image
import imagehash
import numpy as np
import os, re
import sys


bp = Blueprint('image', __name__, url_prefix='/image')

@bp.route('/')
def render_file():
    return render_template('check/imagetest.html')

@bp.route('/fileupload', methods = ['GET', 'POST'])
def upload_file():
    image_hash = []
    search = "/home/ubuntu/Gachon_uni/projects/imagecatch/imca/static/image/image_compare"
    noread = "/home/ubuntu/Gachon_uni/projects/imagecatch/imca/static/image/hashvalue"

    if request.method == 'POST':

        def average_hash(fname, size=16):
            print(fname, sep='\n')

            cache = noread + "/" + fname.replace('/', '_') + ".csv"

            if not os.path.exists(cache):

                img = Image.open(fname)

                img = img.convert('L').resize((size, size), Image.ANTIALIAS)
                pixels = np.array(img.getdata())
                avg = pixels.mean()
                px = 1 * (pixels > avg)
                np.savetxt(cache, px, fmt="%.0f", delimiter=",")

            else:
                print("cache is exist")
                px = np.loadtxt(cache, delimiter=",")

            return px

        def enum_all_files(path):
            for root, dirs, files in os.walk(path):
                for f in files:
                    fname = os.path.join(root, f)
                    fname1 = fname.replace("\\", '/')

                    if re.search(r'\.(jpg|jpeg|png)$', fname):
                        yield fname1

        def hamming_dist(data1, data2):

            image1 = data1.reshape(1, -1)
            image2 = data2.reshape(1, -1)
            dist = (image1 != image2).sum()

            return dist

        def find_image(fname, rate):

            src = average_hash(fname)


            for fname1 in enum_all_files(search):

                dst = average_hash(fname1)
                diff_r = hamming_dist(src, dst) / 256

                if diff_r < rate:
                    f_1 = fname1.replace("\\", '/')

                    f_1_update = os.path.basename(f_1)
                    yield (diff_r, f_1_update)

        #image_test Algorithm
        def image_test(image):
            origininal_image = secure_filename(image.filename)
            print('original_image:', origininal_image)
            img_test = Image.open(image)
            print(img_test)
            print("success")


            img_hash_value = imagehash.average_hash(img_test)
            img_hash_value_r = str(img_hash_value)
            print(img_hash_value_r)

            f = open('/home/ubuntu/Gachon_uni/projects/imagecatch/imca/views/imagehash.txt', 'r')

            image_hash = []

            while True:
                line = f.readline()
                line1 = line.rstrip()
                image_hash.append(line1)

                if not line:
                    break

            f.close()
            print(image_hash)

            #original
            if img_hash_value_r in image_hash:
                print('file already exist')
                img_test.save('/home/ubuntu/Gachon_uni/projects/imagecatch/imca/static/image/' + img_hash_value_r + "_" + origininal_image)
                result_c = img_hash_value_r

            #mimic
            else:
                f = open('/home/ubuntu/Gachon_uni/projects/imagecatch/imca/views/imagehash.txt', 'a')
                f.write('{0}'.format(img_hash_value_r))
                f.write('\n')
                print('success')
                img_test.save('/home/ubuntu/Gachon_uni/projects/imagecatch/imca/static/image/' + img_hash_value_r + "_" + origininal_image)
                result_c = img_hash_value_r

                f.close()

            print(image_hash)
            print(result_c)

            return result_c

        f = request.files['file']
        original = secure_filename(f.filename)
        print(f)

        testimage = image_test(f)

        srcfile = ("/home/ubuntu/Gachon_uni/projects/imagecatch/imca/static/image/" + testimage + "_" + original)

        sim = list(find_image(srcfile, 0.15))
        sim = sorted(sim, key=lambda x: x[0])

    return render_template('check/test.html',  data1= sim, image_file= 'image/' + testimage + '_' + original, image_file1 = 'image/apology.png')

ImageCatch/projects/imagecatch/imca/views/guide_views.py
from flask import Blueprint, url_for, render_template

bp = Blueprint('guide', __name__, url_prefix='/guide')

@bp.route('/')
def content():
    return render_template('guide.html')

ImageCatch/projects/imagecatch/imca/templates/base.html
<!doctype html>
<html lang="ko">
    <head>
        <meta charset="utf-8" >
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" >
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
        <title>ImageCatch</title>
    </head>
    <body class="sb-nav-fixed">
        <div id="layoutSidenav">           
            <div id="layoutSidenav_content">
                {% include "navbar.html" %}
                {% block content %}
                {% endblock %}
                {% include "footer.html" %}
            </div>
        </div>
        <script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='Chart.min.js') }}"></script>
        <script src="{{ url_for('static', filename='scripts.js') }}"></script>
        <script src="{{ url_for('static', filename='all.min.js') }}"></script> 
        {% block script %}
        {% endblock %}
    </body>
</html>

ImageCatch/projects/imagecatch/imca/templates/chart.html
{% extends 'base.html' %}
{% block content %}
<p class="center-block" style="width: 300px; padding:70px;"></p>
<main>
  <div class="container-fluid text-center">
    <div class="container">
      <h1 class="mt-4 md-5">인기 품목 중고 평균가</h1>
      <div class="container mt-5">
        <select class="btn btn-secondary dropdown-toggle" id="Mobility" name="Mobility" onchange="handleOnChange(this)">
          <option selected="">골라주세요.</option>
          <option value="220,000원">에어팟pro</option>
          <option value="495,000원">다이슨 에어랩</option>
          <option value="338,000원">닌텐도스위치</option>
        </select>
      </div>
      <h5 class="text-center mt-4"><b>평균가</b></h5>
      <h1 class="text-center mt-3"><div id='result'></div></h1>
    </div>
  </div>
</main>
{% endblock %}
{% block script %}
<script type='text/javascript'>
var objSelect = document.getElementById("Mobility");

function handleOnChange(e) {
  const value = e.value;
  document.getElementById('result').innerText
    = value;
}
</script>
{% endblock %}

ImageCatch/projects/imagecatch/imca/templates/footer.html
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">&copy; 2021. ImageCatch Co. all rights reserved.</div>
        </div>
    </div>
</footer>

ImageCatch/projects/imagecatch/imca/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

ImageCatch/projects/imagecatch/imca/templates/guide.html
{% extends 'base.html' %}
{% block content %}
<style> .carousel-inner > .carousel-item > img{
     width: 400px; 
     height: 400px; } 
</style>
<main>
    <p class="center-block" style="width: 100px; padding:60px;"></p>
    <div class="container-fluid text-center">
        <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselIndicators" data-slide-to="1"></li>
                <li data-target="#carouselIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="{{ url_for('static', filename='guide_img.jpg') }}" alt="">
                </div>
                <div class="carousel-item">
                    <div class="container">
                        <h1 class="display-4 mt-5">다음의 경우는 100%사기꾼!!!</h1>
                        <pre>




더치트 검색결과 사기 <b>신고내역이 조회</b>되는 경우

판매자가 보내준 안전거래 사이트가 <b>네이버 검색</b>으로 나오지 않는 경우

네이버페이 안전결재시 예금주가 <b>'네이버페이'</b>가 아닌 경우

인증 사진이 다른 곳에서 <b>퍼온사진</b>일 경우

수수로 명목으로 입금 후 <b>재차 입금</b>을 요구하는 경우
                        </pre>
                    </div>
                </div>
                <div class="carousel-item">
                    <div class="container">
                        <h1 class="display-4 mt-5">거래 전 확인해야할 기본적인 사항들!!!</h1>
                        <pre>




제품 사진이 <b>도용된 사진</b>인지 확인해본다

거래 전, <b>중고시세</b>를 찾아본다

판매자 정보로 <b>사기꾼 조회</b>를 해본다

<b>전화번호가 없는 사람</b>은 의심한다

무리한 <b>택배 요구</b>를 하는지 확인한다
                        </pre>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</main>
{% endblock %}

ImageCatch/projects/imagecatch/imca/templates/navbar.html
 <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">ImageCatch</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <div class="input-group-append">
            </div>
        </div>
    </form>
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                {% if g.user %}
                <a class="dropdown-item" href="{{ url_for('auth.checkpasswd') }}">마이페이지</a>
                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
                {% else %}
                <a class="dropdown-item" href="{{ url_for('auth.login') }}">로그인</a>
                <a class="dropdown-item" href="{{ url_for('auth.signup') }}">계정생성</a>
                {% endif %}
            </div>
        </li>
    </ul>
</nav>      
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">                                              
                    <a class="nav-link" href="{{ url_for('image.render_file') }}">
                        <div class="sb-nav-link-icon"><i class="fas fa-images"></i></div>
                        이미지 유사도
                    </a>
                    <a class="nav-link" href="{{ url_for('chart.content') }}">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        평균가
                    </a>                    
                    <a class="nav-link" href="{{ url_for('board._list') }}">
                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                        게시판
                    </a>
                    <a class="nav-link" href="{{ url_for('guide.content') }}">
                        <div class="sb-nav-link-icon"><i class="fas fa-book"></i></div>
                        가이드
                    </a>
                </div>
            </div>
        </nav>
    </div>   
</div>   