ImageCatch/projects/imagecatch/imca/views/board_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from .. import db
from ..forms import BoardForm, CommentForm
from ..models import Board, User
from datetime import datetime
from imca.views.auth_views import login_required

bp = Blueprint('board', __name__, url_prefix='/board')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')

    board_list = Board.query.order_by(Board.create_date.desc())
    if kw:
        search = '%%{}%%'.format(kw)
        board_list = board_list \
            .join(User) \
            .filter(Board.title.ilike(search) |  
                    Board.content.ilike(search) |  
                    User.username.ilike(search)  
                    ) \
            .distinct()

    board_list = board_list.paginate(page, per_page=10)
    return render_template('board/board_list.html', board_list=board_list, page=page, kw=kw)


@bp.route('/detail/<int:board_id>/')
def detail(board_id):
    form = CommentForm()
    board = Board.query.get_or_404(board_id)
    return render_template('board/board_detail.html', board=board, form=form)

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = BoardForm()
    if request.method == 'POST' and form.validate_on_submit() and g.user.permissions == 1:
        board = Board(sections=form.sections.data, title=form.title.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(board)
        db.session.commit()
        return redirect(url_for('board._list'))
    elif request.method == 'POST' and g.user.permissions == 0:
        board = Board(title=form.title.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(board)
        db.session.commit()
        return redirect(url_for('board._list'))
    return render_template('board/board_form.html', form=form)

@bp.route('/modify/<int:board_id>', methods=('GET', 'POST'))
@login_required
def modify(board_id):
    board = Board.query.get_or_404(board_id)
    if g.user != board.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('board.detail', board_id=board_id))
    if request.method == 'POST':
        form = BoardForm()
        if form.validate_on_submit():
            form.populate_obj(board)
            board.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('board.detail', board_id=board_id))
        elif g.user.permissions == 0:
            form.populate_obj(board)
            board.sections = '공지사항'
            board.modify_date = datetime.now() 
            db.session.commit()
            return redirect(url_for('board.detail', board_id=board_id))    
    else:
        form = BoardForm(obj=board)
    return render_template('board/board_form.html', form=form)

@bp.route('/delete/<int:board_id>')
@login_required
def delete(board_id):
    board = Board.query.get_or_404(board_id)
    if g.user != board.user and g.user.permissions != 0:
        flash('삭제권한이 없습니다')
        return redirect(url_for('board.detail', board_id=board_id))
    elif g.user.permissions == 0:
        db.session.delete(board)
        db.session.commit()
        return redirect(url_for('board._list'))
    else:
        db.session.delete(board)
        db.session.commit()
        return redirect(url_for('board._list'))

ImageCatch/projects/imagecatch/imca/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from imca import db
from imca.forms import CommentForm
from imca.models import Board, Comment
from imca.views.auth_views import login_required

bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/create/board/<int:board_id>', methods=('GET', 'POST'))
@login_required
def create_board(board_id):
    form = CommentForm()
    board = Board.query.get_or_404(board_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), board=board)
        db.session.add(comment)
        db.session.commit()
        return redirect('{}#comment_{}'.format(
            url_for('board.detail', board_id=board_id), comment.id))
    return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/board/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify_board(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('board.detail', board_id=comment.board.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect('{}#comment_{}'.format(
                url_for('board.detail', board_id=comment.board.id), comment.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)

@bp.route('/delete/board/<int:comment_id>')
@login_required
def delete_board(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    board_id = comment.board.id
    if g.user != comment.user and g.user.permissions != 0:
        flash('삭제권한이 없습니다')
        return redirect(url_for('board.detail', board_id=board_id))
    elif g.user.permissions == 0:
        db.session.delete(comment)
        db.session.commit()
        return redirect(url_for('board.detail', board_id=board_id))
    else:
        db.session.delete(comment)
        db.session.commit()
        return redirect(url_for('board.detail', board_id=board_id))

ImageCatch/projects/imagecatch/imca/templates/board/board_detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ board.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ board.content }}</div>
            <div class="d-flex justify-content-end">
                {% if board.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ board.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ board.user.username }}</div>
                    <div>{{ board.create_date|datetime }}</div>
                </div>
            </div>
            {% if g.user == board.user %}
            <div class="my-3">
                <a href="{{ url_for('board.modify', board_id=board.id) }}"
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{{ url_for('board.delete', board_id=board.id) }}">삭제</a>
            </div>
            {% elif g.user.permissions == 0 %}
            <div class="my-3">
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{{ url_for('board.delete', board_id=board.id) }}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ board.comment_set|length }}개의 댓글이 있습니다.</h5>
    <form action="{{ url_for('comment.create_board', board_id=board.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <div class="input-group">
            <input {% if not g.user %}disabled{% endif %}
            type="text" name="content" id="content" class="form-control" autocomplete="off">{{ form.content.data or '' }}</input>
            <div class="input-group-append">
                <button type="submit" class="btn btn-sm btn-dark">댓글 달기</button>
            </div>
        </div>       
    </form>
    <div class="mt-1">
        {% if board.comment_set|length > 0 %}
        <div class="mt-3">
            {% for comment in board.comment_set %}
            <a name="comment_{{ comment.id }}"></a>
            <div class="comment py-2 text-muted">
                <span style="font-size:15px"><b>{{ comment.user.username }}</b></span><br>
                <span style="white-space: pre-line; font-size:14px;">{{ comment.content }}</span>
                <span class="float-right" style="font-size:10px">
                    {{ comment.create_date|datetime }}
                    {% if comment.modify_date %}
                    (수정:{{ comment.modify_date|datetime }})
                    {% endif %}
                </span>
                {% if g.user == comment.user %}
                <a href="{{ url_for('comment.modify_board', comment_id=comment.id) }}" class="small">수정</a>,
                <a href="#" class="small delete"
                data-uri="{{ url_for('comment.delete_board', comment_id=comment.id) }}">삭제</a>
                {% elif g.user.permissions == 0 %}
                <a href="#" class="small delete"
                data-uri="{{ url_for('comment.delete_board', comment_id=comment.id) }}">삭제</a>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <hr>
    <a href="{{ url_for('board._list') }}" class="btn btn-dark">목록으로</a>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

ImageCatch/projects/imagecatch/imca/templates/board/board_form.html
{% extends 'base.html' %}
{% block content %}
<br/>
<br/>
<div class="container">
    {% if g.user.permissions == 1 %}
    <h5 class="my-3 border-bottom pb-2">게시판 글쓰기</h5>
    {% else %}
    <h5 class="my-3 border-bottom pb-2">공지사항</h5>
    {% endif %}
    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}

        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}

        {% if g.user.permissions == 1 %}
        <label for="title">구분</label>
        <div>
            <select name=sections method="GET" action="/">
                {% for section in form.sections %}
                <option value="{{ form.sections.data or '' }}" SELECTED>{{ section }}</option>
                {% endfor %}
            </select>
            <p></p>
        </div>
        {% endif %}
        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title" value="{{ form.title.data or '' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <a href="{{ url_for('board._list') }}" class="btn btn-dark">목록으로</a> 
        <button type="submit" class="btn btn-dark float-right">저장하기</button>
    </form>
</div>
{% endblock %}

ImageCatch/projects/imagecatch/imca/templates/board/board_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <p class="center-block" style="width: 300px; padding:30px;"></p>
    <div class="container my-3">
        <table class="table">
            <thead>
                <tr class="text-center thead-dark">
                    <th>번호</th>
                    <th>구분</th>
                    <th style="width:50%">제목</th>
                    <th>글쓴이</th>
                    <th>작성일시</th>
                </tr>
            </thead>
            <tbody>
                {% if board_list %}
                {% for board in board_list.items %}
                <tr class="text-center">
                    <td>{{ board_list.total - ((board_list.page-1) * board_list.per_page) - loop.index0 }}</td>
                    <td>{{ board.sections }}
                    <td class="text-left">
                        <a href="{{ url_for('board.detail', board_id=board.id) }}">{{ board.title }}</a>
                        {% if board.comment_set|length > 0 %}
                        <span class="text-danger small ml-2">{{ board.comment_set|length }}</span>
                        {% endif %}
                    </td>
                    <td>{{ board.user.username }}</td>
                    <td>{{ board.create_date|datetime  }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">게시물이 없습니다.</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
        <ul class="pagination justify-content-center">
            {% if board_list.has_prev %}
            <li class="page-item">
                <a class="page-link" data-page="{{ board_list.prev_num }}" href="#">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            {% for page_num in board_list.iter_pages() %}
            {% if page_num %}
            {% if page_num != board_list.page %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
            </li>
            {% else %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">{{ page_num }}</a>
            </li>
            {% endif %}
            {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if board_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{ board_list.next_num }}" href="#">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <div class="justify-content">
            <div class="float-right">
                {% if g.user.permissions == 1 %}
                <a href="{{ url_for('board.create') }}" class="btn btn-dark">글쓰기</a> 
                {% elif g.user.permissions == 0 %}
                <a href="{{ url_for('board.create') }}" class="btn btn-dark"><small>공지사항 쓰기</small></a> 
                {% else %}
                <a href="{{ url_for('board.create') }}" class="btn btn-dark">글쓰기</a> 
                {% endif %}
            </div>
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
                <div class="input-group-append">
                <button class="btn btn-dark" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
</div>
<form id="searchForm" method="get" action="{{ url_for('board._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}